[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# This rule maps incoming API requests to the correct function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm run dev" # This should run Vite
  targetPort = 5173      # The port Vite runs on
  port = 8888              # The port you access in the browser (localhost:8888)
  publish = "dist"
  autoLaunch = true
