[functions]
  included_files = ["netlify/functions/serviceAccountKey.json"]
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
[[plugins]]
  package = "@netlify/plugin-functions-install-core"