# This is the configuration file for Netlify.

[build]
  # This is the command to build your site.
  command = "npm run build"

  # This is the directory where your serverless functions are located.
  functions = "netlify/functions"

  # This is the directory that contains the built site.
  publish = "dist"

# --- Redirects and Rewrites ---
# Rules are processed in the order they appear in this file.

# RULE 1: API Proxy
# This rule proxies all requests from /api/* to your serverless function.
# This MUST come before the SPA catch-all rule.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 # A 200 status code indicates a rewrite (the URL in the browser bar doesn't change).

# RULE 2: SPA Catch-all
# This rule is essential for Single-Page Applications like Vue.
# It ensures that any request that doesn't match a static file in the `publish` directory
# (like your .js and .css files) is redirected to your index.html file.
# This allows Vue Router to handle the client-side routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
